In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
movies_dataset = pd.read_csv('movies.csv')

In [3]:
movies_dataset.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [4]:
movies_dataset.shape

(1038609, 24)

In [4]:
selected_features = ['genres', 'tagline',  'keywords',  'overview', 'title', 'cast', 'director' ]
print(selected_features)


['genres', 'tagline', 'keywords', 'overview', 'title', 'cast', 'director']


In [5]:
for feature in selected_features:
    movies_dataset[feature] = movies_dataset[feature].fillna('')
    

In [6]:
combined_features = movies_dataset['genres'] +' '+movies_dataset['keywords']+' '+movies_dataset['tagline']+' '+movies_dataset['overview']+' '+movies_dataset['title']

In [7]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      A New Yorker in Shanghai When ambitious New ...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [8]:
# converting the text data to feature vectors
 
vectorizer = TfidfVectorizer()

In [9]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [10]:
print(feature_vectors)

  (0, 1697)	0.22865527290399607
  (0, 3998)	0.186148900296793
  (0, 873)	0.13797142102251092
  (0, 1040)	0.05924374505078072
  (0, 16414)	0.18776424059877814
  (0, 1072)	0.03583170002304267
  (0, 14849)	0.181792484697147
  (0, 8235)	0.15616785082016865
  (0, 2337)	0.11236326092129069
  (0, 21206)	0.16988867141461308
  (0, 2139)	0.11046735118791993
  (0, 3166)	0.06979287750186802
  (0, 13619)	0.12302588320776399
  (0, 21928)	0.17469014757475532
  (0, 14748)	0.054894876723582536
  (0, 13791)	0.1690190409076763
  (0, 21116)	0.03483442452828681
  (0, 6142)	0.20276019905404113
  (0, 11073)	0.046923722388684454
  (0, 12962)	0.16088892646658634
  (0, 15219)	0.2171965201819584
  (0, 3649)	0.14066495928371037
  (0, 241)	0.2223490662171688
  (0, 10538)	0.04085075577277579
  (0, 15173)	0.41813281148173687
  :	:
  (4802, 14520)	0.07225752242279602
  (4802, 9380)	0.09271482180759082
  (4802, 22818)	0.09160596430849925
  (4802, 7364)	0.08341714263733314
  (4802, 14711)	0.06797217051796581
  (4802, 2

In [11]:
similarity = cosine_similarity(feature_vectors)

In [12]:
print(similarity)

[[1.         0.0732955  0.02663966 ... 0.03041624 0.01446755 0.0094369 ]
 [0.0732955  1.         0.05565354 ... 0.06924521 0.0480215  0.02276324]
 [0.02663966 0.05565354 1.         ... 0.02836964 0.01301143 0.01742875]
 ...
 [0.03041624 0.06924521 0.02836964 ... 1.         0.03600362 0.04448283]
 [0.01446755 0.0480215  0.01301143 ... 0.03600362 1.         0.03939306]
 [0.0094369  0.02276324 0.01742875 ... 0.04448283 0.03939306 1.        ]]


In [13]:
print(similarity.shape)

(4803, 4803)


In [21]:
movie_name = input('Enter your favorite movie name:')

Enter your favorite movie name: Avatar


In [22]:
list_of_all_titles = movies_dataset['title'].tolist()

In [23]:
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [25]:
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

In [26]:
print(find_close_match)

['Avatar']


In [27]:
close_match = find_close_match[0]

In [28]:
print(close_match)

Avatar


In [29]:
index_of_the_movie = movies_dataset[movies_dataset.title == close_match]['index'].values[0]

In [30]:
print(index_of_the_movie)

0


In [34]:
similarity_score = list(enumerate(similarity[index_of_the_movie]))

In [35]:
print(similarity_score)

[(0, 1.0), (1, 0.07329549774673373), (2, 0.02663965804760971), (3, 0.04118881033020582), (4, 0.10044384692251185), (5, 0.0463193087241756), (6, 0.026355620574553335), (7, 0.07630759610339086), (8, 0.027512327118056908), (9, 0.03849684819923306), (10, 0.05336126228537035), (11, 0.03528184742448402), (12, 0.031758180147759114), (13, 0.030695741863499326), (14, 0.07761168897605031), (15, 0.04078116509946234), (16, 0.055303964458874665), (17, 0.04285653259265578), (18, 0.07506766614066145), (19, 0.047285503187008034), (20, 0.037151921511345894), (21, 0.02419699911332181), (22, 0.029950193063099213), (23, 0.03267389834649319), (24, 0.03317055770324057), (25, 0.028986384879216027), (26, 0.09786776385585472), (27, 0.10651064638198693), (28, 0.038597753090957816), (29, 0.05122070792166734), (30, 0.035078023122601956), (31, 0.09600675883944237), (32, 0.04967389933294438), (33, 0.042625910715271206), (34, 0.02193147154643841), (35, 0.05831826132026619), (36, 0.09651899048543211), (37, 0.03370810

In [36]:
len(similarity_score)

4803

In [37]:
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

In [38]:
print(sorted_similar_movies)

[(0, 1.0), (1914, 0.19826821870813674), (1531, 0.1871077023781243), (1352, 0.1742043939472573), (461, 0.16633626931998471), (1341, 0.16543400577175651), (661, 0.16394242312519103), (3730, 0.15908803595281776), (239, 0.15733741987141275), (1354, 0.15723998751277235), (3158, 0.1555204744108394), (3604, 0.15419452334406533), (1951, 0.1524447266387968), (4593, 0.14933490244796707), (305, 0.14803474254304985), (300, 0.1434489623749235), (1709, 0.1406496222275797), (529, 0.1381731999677967), (432, 0.13651078774518308), (2198, 0.13595972088204916), (539, 0.13579577618612598), (52, 0.13467640514610166), (549, 0.13444761644330497), (1275, 0.1331406053943348), (2995, 0.13295359107075963), (1318, 0.1322762267661043), (4332, 0.13093552768459732), (369, 0.1303371402449522), (634, 0.12946692445160266), (311, 0.12815664953169337), (373, 0.1279217604922494), (2578, 0.1278295993313181), (56, 0.127544766113783), (2696, 0.12653461279585485), (4108, 0.12538174317647185), (342, 0.1250471995235794), (150, 0

In [41]:
# print the name of similar movies based on the index
 
print('Movies suggested for you : \n')
 
i = 1
 
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_dataset[movies_dataset.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . Avatar
2 . Lifeforce
3 . Moonraker
4 . Gattaca
5 . Lost in Space
6 . The Inhabited Island
7 . Zathura: A Space Adventure
8 . Cargo
9 . Gravity
10 . Space Chimps
11 . Alien
12 . Apollo 18
13 . Space Dogs
14 . Trekkies
15 . Treasure Planet
16 . Starship Troopers
17 . Space Pirate Captain Harlock
18 . Tears of the Sun
19 . Deep Impact
20 . Lockout
21 . Titan A.E.
22 . Transformers: Dark of the Moon
23 . Sphere
24 . Sunshine
25 . Mad Max Beyond Thunderdome
26 . The Thing
27 . Silent Running
28 . Lara Croft Tomb Raider: The Cradle of Life
29 . The Matrix


In [45]:
movie_name = input(' Enter your favourite movie name : ')
 
list_of_all_titles = movies_dataset['title'].tolist()
 
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
 
close_match = find_close_match[0]
 
index_of_the_movie = movies_dataset[movies_dataset.title == close_match]['index'].values[0]
 
similarity_score = list(enumerate(similarity[index_of_the_movie]))
 
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
 
print('Movies suggested for you : \n')
 
i = 1
 
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_dataset[movies_dataset.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite movie name :  Man of steel


Movies suggested for you : 

1 . Man of Steel
2 . Superman II
3 . Superman Returns
4 . X-Men
5 . American Hero
6 . Iron Man 2
7 . Superman
8 . Winter's Tale
9 . I Am Legend
10 . Say It Isn't So
11 . The League of Extraordinary Gentlemen
12 . Superman III
13 . The R.M.
14 . 9
15 . Hercules
16 . Ong Bak 2
17 . X-Men: Apocalypse
18 . Hellboy II: The Golden Army
19 . Broken Vessels
20 . The NeverEnding Story
21 . Stormbreaker
22 . The Incredible Hulk
23 . Titan A.E.
24 . Astro Boy
25 . The Robe
26 . Lady in the Water
27 . Twixt
28 . The Amazing Spider-Man
29 . Mortal Kombat: Annihilation
